# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='planting_time',
            field=models.DateTimeField(null=True),
        ),
    ]
