# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_field_planting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='planted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantings', to='farm.User'),
        ),
    ]
