# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_auto_20161124_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='total_rainfall',
            field=models.FloatField(default=0),
        ),
    ]
