# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_auto_20161124_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='fields',
        ),
    ]
